export enum SettingsDialogId {
    UPDATE_DAO_CONTRACTS_LIST = 'UPDATE_DAO_CONTRACTS_LIST',
    PREPARE_DAO_CONTRACTS_UPDATE = 'PREPARE_DAO_CONTRACTS_UPDATE',
    GOVERNANCE_PROCESS_REQUIRED = 'GOVERNANCE_PROCESS_REQUIRED',
    UNINSTALL_PLUGIN_ALERT = 'UNINSTALL_PLUGIN_ALERT',
    PREPARE_PLUGIN_UNINSTALLATION = 'PREPARE_PLUGIN_UNINSTALLATION',
    INSTALL_HARMONY_VOTING = 'INSTALL_HARMONY_VOTING',
    PREPARE_HARMONY_VOTING_INSTALLATION = 'PREPARE_HARMONY_VOTING_INSTALLATION',
}
